name: ${project.name}
main: de.JeterLP.ChatManager.ChatEX
version: ${project.version}
author: [TheJeterLP, MichelDeStar]
description: Chat management plugin
softdepend: [PermissionsEx,Vault,bPermissions]
